GET http://localhost:3000/api/products HTTP/1.1

###

GET http://localhost:3000/api/products/2 HTTP/1.1

###
POST http://localhost:3000/api/products HTTP/1.1
Content-Type: application/json

    {
        "nombre": "Air Jordan 1 High OG",
        "stock": 25,
        "precio": 170.00,
        "imagen": "img/nike/Air_Jordan_1_High_OG.webp"
    }

### 
PUT http://localhost:3000/api/products/6 HTTP/1.1
Content-Type: application/json

{
    "precio": "199.99"
}


###
DELETE http://localhost:3000/api/products/11 HTTP/1.1